name: deploy to pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_URL: ${{ secrets.API_URL }} 

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: add env
        run: |
          sed -i "s|location|\"${API_URL}\"|g" client/env.js

      - name: upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploy
        id: deployment
        uses: actions/deploy-pages@v4
